### ISSUE TITLE
Can I join the competition with M2 pro chip

### ISSUE THREAD

**Issue by Cklwanfifa** [ContinualAI/clvision-challenge-2024#1]
Hello,

I have a question regarding the hardware restrictions for the competition. It appears that the guidelines presuppose the use of either a GPU or a CPU for model training. However, I am interested in knowing whether the use of an M2 Pro chip is permissible for training purposes?

Given the unique architecture of the M2 Pro, I am concerned that the GPUMemoryChecker might not be applicable or fully functional. Your clarification on this matter would be greatly appreciated.

Thank you for your attention to this inquiry.

**Comment by gigug** [comment]
Hi,

technically any hardware is admissible.

The competition plugins we added give participants an estimate of memory and time consumption for every run. They are non-blocking, meaning that exceeding them won't stop the execution of your code.

Solutions that are admitted to the final stage will be run on our machine (1 NVIDIA TITAN RTX (24Gb GPU) with 64Gb of RAM and 12 CPU cores) and will have to strictly adhere to the limits we set, so these plugins are a way for participants to compare their hardware with our hardware and have an estimate of whether their strategies require too many resources.

If the specific architecture of your machine does not allow for those plugins to work, you can comment them out.

For reference, we ran the baseline strategy LwFUnlabelled and the execution on scenario_1 needed 134m. You can compare your perfomance against this.
