### ISSUE TITLE
Unable to download data

### ISSUE THREAD

**Issue by tanyang1231** [ContinualAI/clvision-challenge-2024#2]
Dear organizers,

We are unable to download the data via wget --content-disposition 'https://files.icg.tugraz.at/f/deb8e57ba0534350a160/?dl=1'. There is a notification: 502 Bad Gateway. Could you please resolve this issue?

**Comment by gigug** [comment]
Hi,

Are you using the ```wget``` script? Could you try to download It manually by visiting the URL?

**Comment by tanyang1231** [comment]
It works now!

**Comment by kpriyanshu256** [comment]
The 502 error is back

**Comment by gigug** [comment]
Hi, can you try downloading it manually by clicking on the URL?

**Comment by kpriyanshu256** [comment]
Thank you, it works now!
