### ISSUE TITLE
The definition of "raw image"

### ISSUE THREAD

**Issue by thkimYonsei** [ContinualAI/clvision-challenge-2024#3]
Hello,

I want to make sure about the definition of "raw image".

By the rule, we cannot store "raw image" into replay buffer. But what exactly is this "raw image"?

I have a confusion that whether the "raw image" includes augmented (data transformation applied) image or not.

I hope anyone can clarify this to me.

Thank you

**Comment by gigug** [comment]
From the updated guidelines, that will soon be published:

Raw images, as well as any straightforward derivatives of them, are not allowed to be stored. Prohibited modifications include, among others: slicing, selecting specific segments of the image, pixel-wise alterations, basic color adjustments and aggregates of multiple images.
