### ISSUE TITLE
The definition of "Max Training Time"

### ISSUE THREAD

**Issue by yzr939** [ContinualAI/clvision-challenge-2024#6]
Hello,

I' d like to confirm whether "Max Training Time" is a total time limit for all three scenarios or a limit for each individual scenario?

Thank you.

**Comment by Tsebeb** [comment]
Hi,

the restriction of the training time is defined per scenario. So you can train up to 10h for each of the 3 scenarios :).

**Comment by yzr939** [comment]
请放心，文件我已经收到了
